### ISSUE TITLE
QSslSocket: Checking presence of openssl library

### ISSUE THREAD

**Issue by xbrakl** [kn0t3k/kyrys#10]
We need OpenSSL library for creating certificates of server app. UNIX and OS X are OK, but not all windows have OpenSSL library, so server app have to check its host computer if has installed this library.

Check explanation in:
http://stackoverflow.com/questions/33198360/qt-with-qsslsocket-not-connecting-properly

**Comment by kn0t3k** [comment]
added dll library to the bin folder, use this together with the certificates, closed
