### ISSUE TITLE
Client JSON message has wrong structure

### ISSUE THREAD

**Issue by kn0t3k** [kn0t3k/kyrys#16]
the correct structure is as follows:
{\"method\": \"register\",\"args\": {\"name\": \"Jan Novak\",\"nick\": \"Jak\"}}

thats why we have test, to show the correct behavior

**Comment by kn0t3k** [comment]
also, no such method as register/call exists - we either have register OR call

**Comment by xbrakl** [comment]
http://erickveil.github.io/2016/04/06/How-To-Manipulate-JSON-With-C++-and-Qt.html

**Comment by xbrakl** [comment]
Structure of JSON messages for registration and login was repaired and improved.
